name: Windows Build
on: [push,create]
jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "VERSION=$(git describe --tags --dirty --always)" >> $GITHUB_ENV

      - name: Make App Image
        uses: addnab/docker-run-action@v3
        with:
          image: cjd1/pkt-electrum-linux-builder@sha256:9c085ac3b13ed5d0b1bcbb097e43f1eed831e291951bcd7cb98a15e5d5def766
          shell: bash
          options: >
            -v ${{ github.workspace }}:/opt/wine64/drive_c/electrum
          run: >
            cd /opt/wine64/drive_c/electrum/contrib/build-wine && /opt/wine64/drive_c/electrum/contrib/build-wine/make_win.sh

      - uses: actions/upload-artifact@main
        with:
          path: contrib/build-wine/dist/*.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: contrib/build-wine/dist/electrum-${{ env.VERSION }}-setup.exe

